<template>
  <div id="template-root p-0 m-0" class="h-screen">
    <!-- <p class="z-50 absolute text-black bg-white">
  <span v-for="c in allCandidates">{{c}}</span>
</p>
 -->
    <section v-if="card=='E'" id="stateError" class="absolute z-50 w-screen flex justify-center items-center">
      <div class="text-center" v-if="error.msg">
        <p>{{error.msg}}</p>
            <p class="text-sm">(generated by {{error.source}})</p>
          </div>
            <div v-else>(no current errors)</div>
    </section><!-- /section.E -->

    <section v-if="card=='Q'" id="queryMenu" class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center">
      <input v-model="query" type="text" id="queryInput" class="block p-4 w-full h-full rounded-sm sm:text-lg focus:ring-blue-500 focus:border-blue-500 text-center">
    </section><!-- /section.Q -->
    
    <section v-if="card=='D'" id="cbbDocument" class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center">

      <!-- <input v-model="cbbDocument" type="text" class="block p-4 w-full h-full rounded-sm sm:text-lg focus:ring-blue-500 focus:border-blue-500 text-center"> -->
    <div class="flex flex-wrap items-stretch w-full mb-4 relative">
      <input v-model="cbbDocument.name" type="text" class="flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border h-50 border-grey-light rounded rounded-r-none px-3 relative" placeholder="name">
    </div>
    <div class="flex flex-wrap items-stretch w-full mb-4 relative">
      <input v-model="cbbDocument.anno" type="text" class="flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border h-50 border-grey-light rounded rounded-r-none px-3 relative" placeholder="anno">
    </div>
    <div class="flex flex-wrap items-stretch w-full mb-4 relative">
      <input v-model="cbbDocument.tagString" type="text" class="flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border h-50 border-grey-light rounded rounded-r-none px-3 relative" placeholder="tagstring">
    </div>

    <div class="flex flex-wrap items-stretch w-full mb-4 relative">{{JSON.stringify(cbbDocument)}}</div>
    
    </section><!-- /section.D -->
    
    <section v-if="card=='R'" id="cbbLiveString" class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center">
      {{cbbDocument.liveString}},
    </section><!-- /section.D -->

    <section class="w-screen flex justify-center items-center">
      <progress :value="loading.progress" max="100" />
    </section>
    <section id="queryResults" class="text-xs absolute z-50 w-screen flex justify-center items-center">
      <div class="z-10 absolute w-48 h-12 rounded-lg bg-green-500">
        <p><span @click="card='Q'">Q</span>*<span @click="card=='D'?card='':card='D'">D</span>*<span @click="card=='E'?card='':card='E'">E</span>*<span @click="card=='R'?card='':card='R'">R</span></p>
        <p><span @click="submitDocument">subm</span></p>
        <!-- <p @click="DEV">DEV</p> -->
        <!-- <p>{{document.name}}::{{document.anno}}::{{document.cartodb_id}}</p> -->
      </div>
      <div v-for="candidate in candidates.features" class="relative w-48 h-12 rounded-lg bg-gray-200 mr-1 p-2">{{launderOSMDisplay(candidate.properties,'display_name')}}
        <p @click="setChoiceGeometry(candidate.properties.osm_id)">({{candidate.geometry.type.toLowerCase()}})</p>
      </div>
    </section>
    <Map class="h-full" :candidates="candidates" :choice="choice" :boundsDefault="boundsDefault" />
  </div>
  <!-- root -->
</template>

<script setup>
import { useRoute, useRouter } from 'vue-router';
import { ref, reactive, computed, onMounted, watch, toRaw } from 'vue';
import { latLngBounds, latLng } from 'leaflet';
import * as turf from '@turf/turf';

import Map from '/src/components/Map.vue';

const LOADING = false;

const ROUTE = useRoute(),
  ROUTER = useRouter(),
  PROPS = defineProps({
    query: String
    ,tags: String
  });

/*
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           @@@@@@ @@@@@@@  @@@@@@  @@@@@@@ @@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          !@@       @@!   @@!  @@@   @@!   @@!
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           !@@!!    @!!   @!@!@!@!   @!!   @!!!:!
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                              !:!   !!:   !!:  !!!   !!:   !!:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          ::.: :     :     :   : :    :    : :: :::
*/
const card = ref('D');
const loading = ref({ iz: false, progress: 0 });
const candidates = ref({});
const choice = ref({ properties: {} });
const cbbDocument = reactive({ name: "",anno:"",liveString:"",tagString:"" });
const error = reactive({ source: null,msg:null });
//
const boundsDefault = [-180, -89.9, 180, 89.9];


/*
888888888888888888888888888888888888888888888888          .,-:::::     ...     .        :::::::::::. ...    :::::::::::::::.,:::::::::::::-.
888888888888888888888888888888888888888888888888        ,;;;'````'  .;;;;;;;.  ;;,.    ;;;`;;;```.;;;;;     ;;;;;;;;;;;'''';;;;'''' ;;,   `';,
888888888888888888888888888888888888888888888888        [[[        ,[[     \[[,[[[[, ,[[[[,`]]nnn]]'[['     [[[     [[      [[cccc  `[[     [[
888888888888888888888888888888888888888888888888        $$$        $$$,     $$$$$$$$$$$"$$$ $$$""   $$      $$$     $$      $$""""   $$,    $$
888888888888888888888888888888888888888888888888        `88bo,__,o,"888,_ _,88P888 Y88" 888o888o    88    .d888     88,     888oo,__ 888_,o8P'
888888888888888888888888888888888888888888888888          "YUMMMMMP" "YMMMMMP" MMM  M'  "MMMYMMMb    "YmmMMMM""     MMM     """"YUMMMMMMMP"`
  */
const cbbResponse = computed(() => {
  return cbbDocument;
});

/*
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  ___      ___   _______  ___________  __    __     ______    ________    ________
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |"  \    /"  | /"     "|("     _   ")/" |  | "\   /    " \  |"      "\  /"       )
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  \   \  //   |(: ______) )__/  \\__/(:  (__)  :) // ____  \ (.  ___  :)(:   \___/
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  /\\  \/.    | \/    |      \\_ /    \/      \/ /  /    ) :)|: \   ) || \___  \
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |: \.        | // ___)_     |.  |    //  __  \\(: (____/ // (| (___\ ||  __/  \\
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |.  \    /:  |(:      "|    \:  |   (:  (  )  :)\        /  |:       :) /" \   :)
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |___|\__/|___| \_______)     \__|    \__|  |__/  \"_____/   (________/ (_______/
*/
const constructDocument = () => {

  let d = new Date();
  let geo = choice.value;
  geo.properties.name=cbbDocument.name;
  geo.properties.anno=cbbDocument.anno;
  geo.properties.tags=cbbDocument.tagString.split(",");
  geo.properties.scnotes="nominatim via milleria JeAKODR2";
  geo.properties.cartodb_id=null;
  geo.properties.created_at=d.toISOString();
  geo.properties.updated_at=d.toISOString();

  // minimizing
delete geo.properties.place_id;
delete geo.properties.osm_type;
delete geo.properties.place_rank
delete geo.properties.category
delete geo.properties.type
delete geo.properties.importance
delete geo.properties.icon
delete geo.properties.address
delete geo.properties.extratags
delete geo.properties.namedetails

return geo;
}


const submitDocument = () => {

let _cbbdoc = constructDocument();
// console.log("_cbbdoc", JSON.stringify(_cbbdoc));
//       error.msg="fetch is turned off";error.source="submitDocument"
  
fetch("http://localhost:3030/v3/cbb/geom", {
    "credentials": "omit",
    "referrer": "http://localhost:9304/",
    "headers": { "Content-Type": "application/json" },
    "body": JSON.stringify(_cbbdoc),
    "method": "POST"
}).then(async r=>{
  cbbDocument.liveString=await r.json();
  card.value='R';
}).catch(e => {
      console.error(e);
      error.msg=e;error.source="submitDocument.POST"
      card.value='E';
    })
;

};

const setChoiceGeometry = (id) => {

  // if wE hAvE A choiCE alrEaDy AND It maTcheS tHe INCoMIng ID, we nULL iT Out
  // oThERWISe wE prObe CaNdIdATES fOR tHE ID aNd set iT
  let newChoice = choice.value.properties.osm_id == id ? {} : candidates.value.features.find(fea => {
    return fea.properties.osm_id == id;
  });

  choice.value = newChoice;
  cbbDocument.name=newChoice.properties.display_name;
};

const launderOSMDisplay = (fea, prop) => {
  /*
  osM dIsPLay names arE tYpICALLY prETTY GNarLy - FoR oUr PUrposES heRe ThE FiRsT fEW clausES WILl SUFFICe
  */
  return fea.valueOf()[prop].split(",").filter((propel, propeli) => {
    return propeli < 3 ? propel : null;
  }).join(", ")
}

const normalizeOSM = (features) => {

  /*
  ouR OSm REsultS wiLL TYPicAlLy be a fEaTurECOlLEctION StEw OF pOLYS ANd LInEs anD PoInts
  vue-LeAFlET *sEems* LiKe iT wOULd dO pOINttOlAyER (ENABLInG circlEmARkeRs fOR THE poINtS) BUt IT aIN'T WORking
  In hErE, tHErEfORE, we JuST bUffer The PointS inTO pOLYS
  */

  return features.map(fea => {

    // cLoNE THE pROps
    let propsClone = structuredClone(fea.properties);

    // if IT'S A PoInt rEplaCe IT W/ a BuFFeR ANd updatE tHe Bbox
    let newFeature = fea.geometry.type == "Point" ? turf.buffer(fea, 10, { units: 'kilometers' }) : fea;
    // INdICaTE oUr sHenANiGaNs IN tHE PrOpS
    newFeature.properties.provenance = fea.geometry.type == "Point" ? "turf.buffer" : "og";
    newFeature.bbox = fea.geometry.type == "Point" ? turf.bbox(newFeature) : fea.bbox;
    return newFeature;

  });
}

const animateProgress = () => {
  loading.value.progress++;
  setTimeout(() => {}, 10100);
};

const getCandidates = () => {

    // LOOK AT All tHIS SHIT We NEeD fOr a DumB proGRESs baR
    setTimeout(() => {}, 60100);
    setTimeout(() => {
      let intervalID = setInterval(() => {
        if (loading.value.progress === 100) {
          clearInterval(intervalID);
        } else {
          animateProgress();
        }
      }, 100); //tHis SETS the speEd OF tHE AniMatiOn
    }, 1000);


    // GeT ThE stuFF
    fetch(`https://nominatim.openstreetmap.org/search?q=${PROPS.query}&format=geojson&polygon_geojson=1&email=lennybones@ymail.com&dedupe=1&addressdetails=1&extratags=1&namedetails=1`, {
      headers: { 'Access-Control-Allow-Origin': '*' },
      "method": "GET",
      "mode": "cors"
    }).then(async res => {

      setTimeout(() => {}, 60100);
      loading.value.progress = 100;
      loading.value.iz = false;

      // to LOCAl OBject
      let response = await res.json();

      // WORkINg cOpy oF tHE feaTuREs themseLVES
      let features = response.features;
      let featuresClone = structuredClone(response.features);


      // Before we Set theSE TO VUe  LETS rOOt arOuNd in ThERE and tAKE tHosE godAm fUggin pOints aND BUFfEr EM INtO polYS (LCircleMarker workaround)
      let normalizedFeatures = normalizeOSM(featuresClone);

      response.features = normalizedFeatures;
      candidates.value = response;

    }).catch(e => {
      console.error(e);
      error.msg=e;error.source="getCandidates.GET"
    });
  } //getcandidates



onMounted(() => {
  PROPS.query && console.info(`incoming query is ${PROPS.query} so we wanna fire the geocode here`);
  PROPS.tags && console.info(`incoming tags exists so we wanna decode and posthaste make it the cbbDocument.tagString`);
  cbbDocument.tagString = PROPS.tags ?decodeURI(PROPS.tags):null;
  PROPS.query && getCandidates()
});
</script>

<style>
body {
  font-family: 'overpass';
  font-weight: 800;
}

#stateError {
  background-color: rgba(230, 57, 70,.9);color: rgb(241, 250, 238);font-weight: 900;font-size: 2em;
  height: 25vh;
  top: 50%;
}
#cbbDocument {
  background-color: rgba(244, 244, 244, .5);
  height: 25vh;
  top: 50%;
}
#cbbLiveString {
  background-color: rgba(2, 2, 2, 9);color: white;font-weight: 900;
  font-size: 3em;
  height: 100vh;
  top: 0%;
}
#queryMenu {
  background-color: rgba(244, 244, 244, .5);
  height: 25vh;
  top: 50%;
}
#queryInput {
  font-size: 3em;
}

#queryResults {
  top: 2em;
  background-color: rgba(244, 244, 244, .9);
}

.cbb-document-input {
  font-size: 2em;
}

progress[value] {
  width: 100%;
  height: 12px;
  border-radius: 2px;
}
</style>
