<template>
  <div id="template-root p-0 m-0" class="h-screen">
    <!-- <p class="z-50 absolute text-black bg-white">
  <span v-for="c in allCandidates">{{c}}</span>
</p>
 -->
    <section v-if="card=='E'" id="stateError" class="absolute z-50 w-screen flex justify-center items-center">
      <div class="text-center" v-if="error.msg">
        <p>{{error.msg}}</p>
            <p class="text-sm">(generated by {{error.source}})</p>
          </div>
            <div v-else>(no current errors)</div>
    </section><!-- /section.E -->

    <section v-if="card=='Q'" id="queryMenu" class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center">
      <div class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-2xl md:mx-auto">
      <form id="cbbQueryForm" class="md:flex md:flex-wrap md:justify-between" @submit.prevent="getCandidates" method="post">
      <input v-model="query" type="text" id="queryInput" class="block p-4 w-full h-full rounded-sm sm:text-lg focus:ring-blue-500 focus:border-blue-500 text-center">
    </form></div>
    </section><!-- /section.Q -->
    
    <section v-if="card=='D'" id="cbbDocument" class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center">

      
    <!-- <div class="flex flex-wrap items-stretch w-full mb-4 relative">
      <input v-model="cbbDocument.name" type="text" class="flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border h-50 border-grey-light rounded rounded-r-none px-3 relative" placeholder="name">
    </div>
    <div class="flex flex-wrap items-stretch w-full mb-4 relative">
      <input v-model="cbbDocument.anno" type="text" class="flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border h-50 border-grey-light rounded rounded-r-none px-3 relative" placeholder="anno">
    </div>
    <div class="flex flex-wrap items-stretch w-full mb-4 relative">
      <input v-model="cbbDocument.tagString" type="text" class="flex-shrink flex-grow flex-auto leading-normal w-px flex-1 border h-50 border-grey-light rounded rounded-r-none px-3 relative" placeholder="tagstring">
    </div> -->

  <div class="flex items-center h-screen w-full">
  <div class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-2xl md:mx-auto">
    <form id="cbbDocumentForm" class="mb-4 md:flex md:flex-wrap md:justify-between" @submit.prevent="submitDocument" method="post">
      <!-- <div class="flex flex-col mb-4 md:w-1/2">
        <label class="mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest" for="first_name">First Name</label>
        <input class="border py-2 px-3 text-grey-darkest md:mr-2" type="text" name="first_name" id="first_name">
      </div> -->
      <!-- <div class="flex flex-col mb-4 md:w-1/2">
        <label class="mb-2 uppercase font-bold text-lg text-grey-darkest md:ml-2" for="last_name">Last Name</label>
        <input class="border py-2 px-3 text-grey-darkest md:ml-2" type="text" name="last_name" id="last_name">
      </div> -->
      <div class="flex flex-col mb-4 md:w-full">
        <label class="text-stone-500 mb-2 uppercase text-lg" for="email">name</label>
        <input v-model="cbbDocument.name" class="border py-2 px-3 text-grey-darkest" type="text" name="name">
      </div>
      <div class="flex flex-col mb-4 md:w-full">
        <label class="text-stone-500 mb-2 uppercase text-lg" for="email">anno</label>
        <input v-model="cbbDocument.anno" class="border py-2 px-3 text-grey-darkest" type="text" name="anno">
      </div>
      <div class="flex flex-col mb-4 md:w-full">
        <label class="text-stone-500 mb-2 uppercase text-lg" for="email">tagString</label>
        <input v-model="cbbDocument.tagString" class="border py-2 px-3 text-grey-darkest" type="text" name="tagString">
      </div>
      <!-- <div class="flex flex-col mb-6 md:w-full">
        <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="password">Password</label>
        <input class="border py-2 px-3 text-grey-darkest" type="password" name="password" id="password">
      </div> -->
      <button class="block text-black uppercase text-lg mx-auto p-4 rounded" type="submit">submit</button>
    </form>
  </div>
</div>
    
    </section><!-- /section.D -->
    
    <section v-if="card=='R'" id="cbbLiveString" class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center">
      {{cbbDocument.liveString}},
    </section><!-- /section.D -->

    <section class="w-screen flex justify-center items-center">
      <progress :value="loading.progress" max="100" />
    </section>

    <section class="w-screen flex justify-center items-center">
    <div class="z-10 absolute w-48 h-12 rounded-lg bg-green-500">
        <!-- <p><span @click="setCard('Q')">Q</span>*<span @click="card=='D'?card='':card='D'">D</span>*<span @click="card=='E'?card='':card='E'">E</span>*<span @click="card=='R'?card='':card='R'">R</span></p> -->
        <p><span @click="submitDocument">subm</span></p>
        <!-- <p @click="DEV">DEV</p> -->
        <!-- <p>{{document.name}}::{{document.anno}}::{{document.cartodb_id}}</p> -->
      </div>
    </section>
    <section id="queryResults" class="text-xs absolute z-50 w-screen flex justify-center items-center">
      <div v-for="candidate in candidates.features" class="relative w-48 h-12 rounded-lg bg-gray-200 mr-1 p-2">{{launderNameString(candidate.properties?.display_name?candidate.properties.display_name:candidate.properties.name)}}
        <p @click="setChoiceGeometry(candidate.properties.osm_id)">({{candidate.geometry.type.toLowerCase()}})</p>
      </div>
    </section>
    <Map class="h-full" :candidates="candidates" :choice="choice" :boundsDefault="boundsDefault" />
  </div>
  <!-- root -->
</template>

<script setup>
import { useRoute, useRouter } from 'vue-router';
import { ref, reactive, computed, onMounted, watch, toRaw } from 'vue';
import CONFIG from '../CONFIG.json'
import { latLngBounds, latLng } from 'leaflet';
import * as turf from '@turf/turf';

import Map from '/src/components/Map.vue';

const LOADING = false;

const ROUTE = useRoute(),
  ROUTER = useRouter(),
  PROPS = defineProps({
    query: String
    ,tags: String
    ,anno: String
  });

/*
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           @@@@@@ @@@@@@@  @@@@@@  @@@@@@@ @@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          !@@       @@!   @@!  @@@   @@!   @@!
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           !@@!!    @!!   @!@!@!@!   @!!   @!!!:!
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                              !:!   !!:   !!:  !!!   !!:   !!:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          ::.: :     :     :   : :    :    : :: :::
*/
const card = ref('D');
const cardKeys=['D','E','Q','R'];
const loading = ref({ iz: false, progress: 0 });
const candidates = ref({});
const choice = ref({ properties: {} });
const cbbDocument = reactive({ name: "",anno:"",liveString:"",tagString:"" });
const error = reactive({ source: null,msg:null });
const dropzone = reactive({state:"",msg:""});
//
const boundsDefault = [-180, -89.9, 180, 89.9];


/*
888888888888888888888888888888888888888888888888          .,-:::::     ...     .        :::::::::::. ...    :::::::::::::::.,:::::::::::::-.
888888888888888888888888888888888888888888888888        ,;;;'````'  .;;;;;;;.  ;;,.    ;;;`;;;```.;;;;;     ;;;;;;;;;;;'''';;;;'''' ;;,   `';,
888888888888888888888888888888888888888888888888        [[[        ,[[     \[[,[[[[, ,[[[[,`]]nnn]]'[['     [[[     [[      [[cccc  `[[     [[
888888888888888888888888888888888888888888888888        $$$        $$$,     $$$$$$$$$$$"$$$ $$$""   $$      $$$     $$      $$""""   $$,    $$
888888888888888888888888888888888888888888888888        `88bo,__,o,"888,_ _,88P888 Y88" 888o888o    88    .d888     88,     888oo,__ 888_,o8P'
888888888888888888888888888888888888888888888888          "YUMMMMMP" "YMMMMMP" MMM  M'  "MMMYMMMb    "YmmMMMM""     MMM     """"YUMMMMMMMP"`
  */
const cbbResponse = computed(() => {
  return cbbDocument;
});

/*
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  ___      ___   _______  ___________  __    __     ______    ________    ________
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |"  \    /"  | /"     "|("     _   ")/" |  | "\   /    " \  |"      "\  /"       )
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  \   \  //   |(: ______) )__/  \\__/(:  (__)  :) // ____  \ (.  ___  :)(:   \___/
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  /\\  \/.    | \/    |      \\_ /    \/      \/ /  /    ) :)|: \   ) || \___  \
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |: \.        | // ___)_     |.  |    //  __  \\(: (____/ // (| (___\ ||  __/  \\
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |.  \    /:  |(:      "|    \:  |   (:  (  )  :)\        /  |:       :) /" \   :)
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |___|\__/|___| \_______)     \__|    \__|  |__/  \"_____/   (________/ (_______/
*/
const setCard = (key) => {
  console.log("key", key);
// is this is a valid card, even?
let cardKey = cardKeys.find(k=>k==key.toUpperCase());
// if it's the current card we toggle off
let newCard = cardKey==card.value ? null:cardKey;
card.value=newCard;
}//setcard

const constructDocument = () => {

  let d = new Date();
  let geo = choice.value;
  geo.properties.name=cbbDocument.name;
  geo.properties.anno=cbbDocument.anno;
  geo.properties.tags=cbbDocument.tagString.split(",").map(ts=>ts.trim());
  geo.properties.scnotes="nominatim via milleria JeAKODR2";
  geo.properties.cartodb_id=null;
  geo.properties.created_at=d.toISOString();
  geo.properties.updated_at=d.toISOString();

  // minimizing
delete geo.properties.place_id;
delete geo.properties.osm_type;
delete geo.properties.place_rank
delete geo.properties.category
delete geo.properties.type
delete geo.properties.importance
delete geo.properties.icon
delete geo.properties.address
delete geo.properties.extratags
delete geo.properties.namedetails

return geo;
}


const submitDocumentFake = () => {
  console.log("fake submitDocument")
}
const submitDocument = () => {

let _cbbdoc = constructDocument();
  
fetch("http://localhost:3030/v3/cbb/geom", {
    "credentials": "omit",
    "referrer": "http://localhost:9304/",
    "headers": { "Content-Type": "application/json" },
    "body": JSON.stringify(_cbbdoc),
    "method": "POST"
}).then(async r=>{
  cbbDocument.liveString=await r.json();
  card.value='R';
}).catch(e => {
      console.error(e);
      error.msg=e;error.source="submitDocument.POST"
      card.value='E';
    })
;

};

const setChoiceGeometry = (id) => {

  // if wE hAvE A choiCE alrEaDy AND It maTcheS tHe INCoMIng ID, we nULL iT Out
  // oThERWISe wE prObe CaNdIdATES fOR tHE ID aNd set iT
  let newChoice = choice.value.properties.osm_id == id ? {} : candidates.value.features.find(fea => {
    return fea.properties.osm_id == id;
  });

  choice.value = newChoice;
  cbbDocument.name=newChoice.properties?.display_name;
};

const launderNameString = (nameString) => {
  /*
  osM dIsPLay names arE tYpICALLY prETTY GNarLy - FoR oUr PUrposES heRe ThE FiRsT fEW clausES WILl SUFFICe
  */
  return nameString?nameString.split(",").filter((propel, propeli) => {
    return propeli < 3 ? propel : null;
  }).join(", "):"no name prop";
}

const normalizeOSM = (features) => {

  /*
  ouR OSm REsultS wiLL TYPicAlLy be a fEaTurECOlLEctION StEw OF pOLYS ANd LInEs anD PoInts
  vue-LeAFlET *sEems* LiKe iT wOULd dO pOINttOlAyER (ENABLInG circlEmARkeRs fOR THE poINtS) BUt IT aIN'T WORking
  In hErE, tHErEfORE, we JuST bUffer The PointS inTO pOLYS
  */

  return features.map(fea => {

    // cLoNE THE pROps
    let propsClone = structuredClone(fea.properties);

    // if IT'S A PoInt rEplaCe IT W/ a BuFFeR ANd updatE tHe Bbox
    let newFeature = fea.geometry.type == "Point" ? turf.buffer(fea, 10, { units: 'kilometers' }) : fea;
    // INdICaTE oUr sHenANiGaNs IN tHE PrOpS
    newFeature.properties.provenance = fea.geometry.type == "Point" ? "turf.buffer" : "og";
    newFeature.bbox = fea.geometry.type == "Point" ? turf.bbox(newFeature) : fea.bbox;
    return newFeature;

  });
}

const animateProgress = () => {
  loading.value.progress++;
  setTimeout(() => {}, 10100);
};

const acceptDrop = (drop) => {

let dro=drop[0];

      
      const reader = new FileReader();
      reader.loadend = e => {
        delete e.target.result;
      };
      reader.onload = D => {

let d=JSON.parse(D.target.result);
console.log("d", d);
d.features=d.features.map(dd=>{
  dd.properties={
                "place_id": null,
                "display_name": "(manual geojson)",osm_id:0
            }
            return dd;
})

      candidates.value = d;
  cbbDocument.name="dropped geojson";
        
      } //reader.onload

      reader.readAsText(dro, "UTF-8");

};//acceptdrop

const getCandidates = () => {

    // LOOK AT All tHIS SHIT We NEeD fOr a DumB proGRESs baR
    setTimeout(() => {}, 60100);
    setTimeout(() => {
      let intervalID = setInterval(() => {
        if (loading.value.progress === 100) {
          clearInterval(intervalID);
        } else {
          animateProgress();
        }
      }, 100); //tHis SETS the speEd OF tHE AniMatiOn
    }, 1000);


    // GeT ThE stuFF
    fetch(`https://nominatim.openstreetmap.org/search?q=${PROPS.query}&format=geojson&polygon_geojson=1&email=lennybones@ymail.com&dedupe=1&addressdetails=1&extratags=1&namedetails=1`, {
      headers: { 'Access-Control-Allow-Origin': '*' },
      "method": "GET",
      "mode": "cors"
    }).then(async res => {

      setTimeout(() => {}, 60100);
      loading.value.progress = 100;
      loading.value.iz = false;

      // to LOCAl OBject
      let response = await res.json();

      // WORkINg cOpy oF tHE feaTuREs themseLVES
      let features = response.features;
      let featuresClone = structuredClone(response.features);


      // Before we Set theSE TO VUe  LETS rOOt arOuNd in ThERE and tAKE tHosE godAm fUggin pOints aND BUFfEr EM INtO polYS (LCircleMarker workaround)
      let normalizedFeatures = normalizeOSM(featuresClone);

      response.features = normalizedFeatures;
      candidates.value = response;

    }).catch(e => {
      console.error(e);
      error.msg=e;error.source="getCandidates.GET"
    });
  } //getcandidates



onMounted(() => {
  
  /* ++++++++++++++++++++++++++++++++++++++++++ dropzone */
    window.addEventListener("dragenter", e => {
      // console.log("in dragenter, e:", e);
      dropzone.state = "drag";
      dropzone.msg = "drop fil";
    });

    window.addEventListener("dragleave", e => {
      e.preventDefault();
      dropzone.state = "idle";
      dropzone.msg = "fil drop";
    });

    window.addEventListener("dragover", e => {
      e.preventDefault();
      dropzone.state = "drag";
    });

    window.addEventListener("drop", e => {
      e.preventDefault();
      dropzone.state = "idle";
      dropzone.msg = "tnx";

      let fil = e.dataTransfer.files;
      acceptDrop(fil);
    });

    /* ++++++++++++++++++++++++++++++++++++++++++ /dropzone */

    /*
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys          ____ ____ ____ ____
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys         ||k |||e |||y |||s ||
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys         ||__|||__|||__|||__||
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys         |/__\|/__\|/__\|/__\|
    */

    document.onkeydown = (e)=>{
    // if (e.key === "s" && (e.ctrlKey || e.metaKey)) {
    //     e.preventDefault(); // present "Save Page" from getting triggered.

    //     alert("The shortcut was pressed");
    // }
    !document.activeElement.form && setCard(e.key);
    
};


  PROPS.query && console.info(`incoming query is ${PROPS.query} so we wanna fire the geocode here`);
  PROPS.tags && console.info(`incoming tags exists so we wanna decode and posthaste make it the cbbDocument.tagString`);
  cbbDocument.tagString = PROPS.tags ?decodeURI(PROPS.tags):null;
  PROPS.anno && console.info(`incoming anno exists so we wanna decode and posthaste make it the cbbDocument.anno`);
  cbbDocument.anno = PROPS.anno ?decodeURI(PROPS.anno):null;
  PROPS.query && getCandidates()
});
</script>

<style>
body {
  font-family: 'overpass';
  font-weight: 800;
}

#stateError {
  background-color: rgba(230, 57, 70,.9);color: rgb(241, 250, 238);font-weight: 900;font-size: 2em;
  height: 25vh;
  top: 50%;
}
#cbbDocument {
  background-color: rgba(244, 244, 244, 0);
  height: 25vh;
  top: 50%;
}
#cbbDocumentForm{font-size: 3em;}
#cbbLiveString {
  background-color: rgba(2, 2, 2, 9);color: white;font-weight: 900;
  font-size: 3em;
  height: 100vh;
  top: 0%;
}
#queryMenu {
  background-color: rgba(244, 244, 244, 0);
  height: 25vh;
  top: 40%;
}
#queryInput {
  font-size: 5em;
}

#queryResults {
  top: 2em;
  background-color: rgba(244, 244, 244, .9);
}

.cbb-document-input {
  font-size: 2em;
}

progress[value] {
  width: 100%;
  height: 12px;
  border-radius: 2px;
}
</style>
