<template>
  <div id="template-root p-0 m-0" class="h-screen">
    <!-- <p class="z-50 absolute text-black bg-white">
  <span v-for="c in allCandidates">{{c}}</span>
</p>
 -->
    <section
      v-if="card == 'E'"
      id="stateError"
      class="absolute z-50 w-screen flex justify-center items-center"
    >
      <div class="text-center" v-if="error.msg">
        <p>{{ error.msg }}</p>
        <p class="text-sm">(generated by {{ error.source }})</p>
      </div>
      <div v-else>(no current errors)</div>
    </section>
    <!-- /section.E -->

    <section
      v-if="card == 'Q'"
      id="queryMenu"
      class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center"
    >
      <div
        class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-2xl md:mx-auto"
      >
        <form
          id="cbbQueryForm"
          class="md:flex md:flex-wrap md:justify-between"
          @submit.prevent="getCandidates"
          method="post"
        >
          <input
            v-model="queryString"
            type="text"
            id="queryInput"
            class="block p-4 w-full h-full rounded-sm sm:text-lg focus:ring-blue-500 focus:border-blue-500 text-center"
          />
          <a href="" @click.prevent="invertCoordinates"
            ><font-awesome-icon class="ml-2 app-copy-5" icon="right-left"
          /></a>
        </form>
      </div>
    </section>
    <!-- /section.Q -->

    <section
      v-if="card == 'D'"
      id="cbbDocument"
      class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center"
    >
      <div class="flex items-center h-screen w-full">
        <div
          class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-2xl md:mx-auto"
        >
          <form
            id="cbbDocumentForm"
            class="mb-4 md:flex md:flex-wrap md:justify-between"
            @submit.prevent="submitDocument"
            method="post"
          >
            <div class="flex flex-col mb-4 md:w-full">
              <label class="text-stone-500 mb-2 uppercase text-lg" for="email"
                >name</label
              >
              <input
                v-model="cbbDocument.name"
                class="border py-2 px-3 text-grey-darkest"
                type="text"
                name="name"
              />
            </div>
            <div class="flex flex-col mb-4 md:w-full">
              <label class="text-stone-500 mb-2 uppercase text-lg" for="email"
                >anno</label
              >
              <input
                v-model="cbbDocument.anno"
                class="border py-2 px-3 text-grey-darkest"
                type="text"
                name="anno"
              />
            </div>
            <div class="flex flex-col mb-4 md:w-full">
              <label class="text-stone-500 mb-2 uppercase text-lg" for="email"
                >tagString</label
              >
              <input
                v-model="cbbDocument.tagString"
                class="border py-2 px-3 text-grey-darkest"
                type="text"
                name="tagString"
              />
            </div>
            <button
              class="block text-black uppercase text-lg mx-auto p-4 rounded"
              type="submit"
            >
              submit
            </button>
          </form>
        </div>
      </div>
    </section>
    <!-- /section.D -->

    <section
      v-if="card == 'R'"
      id="cbbLiveString"
      class="absolute z-50 w-screen flex bg-gray-100 justify-center items-center"
    >
      {{
        cbbDocument.liveString.length > 2
          ? cbbDocument.liveString
          : "nO lIvEsTrING"
      }},
    </section>
    <!-- /section.D -->

    <section class="w-screen flex justify-center items-center">
      <progress :value="loading.progress" max="100" />
    </section>

    <!-- 
                                         ##               ##
                                          ##    #          ##
                                          ##   ###         ##                #
                                          ##    #          ##               ##
                                          ##               ##               ##
       /###      /###   ###  /###     ### ##  ###      ### ##    /###     ######## /##       /###
      / ###  /  / ###  / ###/ #### / ######### ###    ######### / ###  / ######## / ###     / #### /
     /   ###/  /   ###/   ##   ###/ ##   ####   ##   ##   #### /   ###/     ##   /   ###   ##  ###/
    ##        ##    ##    ##    ##  ##    ##    ##   ##    ## ##    ##      ##  ##    ### ####
    ##        ##    ##    ##    ##  ##    ##    ##   ##    ## ##    ##      ##  ########    ###
    ##        ##    ##    ##    ##  ##    ##    ##   ##    ## ##    ##      ##  #######       ###
    ##        ##    ##    ##    ##  ##    ##    ##   ##    ## ##    ##      ##  ##              ###
    ###     / ##    /#    ##    ##  ##    /#    ##   ##    /# ##    /#      ##  ####    /  /###  ##
     ######/   ####/ ##   ###   ###  ####/      ### / ####/    ####/ ##     ##   ######/  / #### /
      #####     ###   ##   ###   ###  ###        ##/   ###      ###   ##     ##   #####      ###/



 -->
    <section
      id="queryResults"
      class="text-xs absolute z-50 w-screen flex justify-center items-center m-auto"
    >
      <div
        @click="setChoiceGeometry(candidate.properties.osm_id)"
        v-for="candidate in candidates.features"
        :class="[
          'app-copy-1',
          candidate.properties.osm_id == choice.properties.osm_id
            ? 'app-bg-4'
            : 'bg-gray-200',
          candidate.properties.osm_id == choice.properties.osm_id
            ? 'app-bg-4'
            : 'hover:bg-gray-100',
          'relative',
          'w-full',
          'h-8',
          'rounded-sm',
          'cursor-pointer',
          'mr-1',
          'p-2',
          'align-middle',
          'inline-block',
        ]"
      >
        <p class="text-center">
          <span
            v-for="(stringSegment, stringSegmenti) in launderNameString(
              candidate.properties?.display_name
                ? candidate.properties.display_name
                : candidate.properties.name
            ).split(',')"
            :class="[stringSegmenti == 0 ? 'app-copy-1' : 'app-copy-1-off-2']"
          >
            {{ stringSegment }}
          </span>
          <font-awesome-icon
            class="ml-2 app-copy-5"
            :icon="geometryIcon(candidate.geometry.type)"
          />
        </p>
      </div>
    </section>
    <Map
      class="h-full"
      :candidates="candidates"
      :choice="choice"
      :boundsDefault="boundsDefault"
    />

    <!-- 
######## ######## ######## ######## ######## ########
##       #####    #####    ###      ##       ###
##   ### ###   ## ###   ## ######   ##   ### ###   ##
##       ##   ### ##   ### ######   ##       ###   ##
##   ### ##   ### ##   ### ######   ##   ### ###
##   ### ###   ## ###   ## ######   ##   ### ###   ##
##   ### #####    #####    ######   ##       ###   ##
######## ######## ######## ######## ######## ######## 
-->
    <footer id="footer" class="h-10 z-60 pb-5 mb-5 ml-2">
      <span
        v-for="_card in ['D', 'E', 'Q', 'R']"
        :class="_card == card ? 'app-copy-on' : 'app-copy-off'"
        >{{ _card }}</span
      >
    </footer>
  </div>
  <!-- root -->
</template>

<script setup>
import { useRoute, useRouter } from "vue-router";
import { ref, reactive, computed, onMounted, watch, toRaw } from "vue";
import CONFIG from "../CONFIG.json";
import { latLngBounds, latLng } from "leaflet";
import * as turf from "@turf/turf";

import Map from "/src/components/Map.vue";

const LOADING = false;

const ROUTE = useRoute(),
  ROUTER = useRouter(),
  PROPS = defineProps({
    query: String,
    tags: String,
    anno: String,
  });

/*
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           @@@@@@ @@@@@@@  @@@@@@  @@@@@@@ @@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          !@@       @@!   @@!  @@@   @@!   @@!
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           !@@!!    @!!   @!@!@!@!   @!!   @!!!:!
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                              !:!   !!:   !!:  !!!   !!:   !!:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          ::.: :     :     :   : :    :    : :: :::
*/
const card = ref("Q");
const queryString = ref("");
const cardKeys = ["D", "E", "Q", "R"];
const loading = ref({ iz: false, progress: 0 });
const candidates = ref({});
const choice = ref({ properties: {} });
const cbbDocument = reactive({
  name: "",
  anno: "",
  liveString: "",
  tagString: "",
});
const error = reactive({ source: null, msg: null });
const dropzone = reactive({ state: "", msg: "" });
//
const boundsDefault = [-180, -89.9, 180, 89.9];

/*
888888888888888888888888888888888888888888888888          .,-:::::     ...     .        :::::::::::. ...    :::::::::::::::.,:::::::::::::-.
888888888888888888888888888888888888888888888888        ,;;;'````'  .;;;;;;;.  ;;,.    ;;;`;;;```.;;;;;     ;;;;;;;;;;;'''';;;;'''' ;;,   `';,
888888888888888888888888888888888888888888888888        [[[        ,[[     \[[,[[[[, ,[[[[,`]]nnn]]'[['     [[[     [[      [[cccc  `[[     [[
888888888888888888888888888888888888888888888888        $$$        $$$,     $$$$$$$$$$$"$$$ $$$""   $$      $$$     $$      $$""""   $$,    $$
888888888888888888888888888888888888888888888888        `88bo,__,o,"888,_ _,88P888 Y88" 888o888o    88    .d888     88,     888oo,__ 888_,o8P'
888888888888888888888888888888888888888888888888          "YUMMMMMP" "YMMMMMP" MMM  M'  "MMMYMMMb    "YmmMMMM""     MMM     """"YUMMMMMMMP"`
  */
const cbbResponse = computed(() => {
  return cbbDocument;
});

/*
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  ___      ___   _______  ___________  __    __     ______    ________    ________
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |"  \    /"  | /"     "|("     _   ")/" |  | "\   /    " \  |"      "\  /"       )
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  \   \  //   |(: ______) )__/  \\__/(:  (__)  :) // ____  \ (.  ___  :)(:   \___/
"""""""""""""""""""""""""""""""""""""""""""""""""""""                  /\\  \/.    | \/    |      \\_ /    \/      \/ /  /    ) :)|: \   ) || \___  \
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |: \.        | // ___)_     |.  |    //  __  \\(: (____/ // (| (___\ ||  __/  \\
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |.  \    /:  |(:      "|    \:  |   (:  (  )  :)\        /  |:       :) /" \   :)
"""""""""""""""""""""""""""""""""""""""""""""""""""""                 |___|\__/|___| \_______)     \__|    \__|  |__/  \"_____/   (________/ (_______/
*/

const setRoute = () => {
  let r = {
    title: "JEAKODR",
    params: {
      query: queryString.value,
      anno: PROPS.anno,
      tags: PROPS.tags,
    },
  };
  ROUTER.push(r);
};

const setCard = (key) => {
  // is this is a valid card, even?
  let cardKey = cardKeys.find((k) => k == key.toUpperCase());
  // if it's the current card we toggle off
  let newCard = cardKey == card.value ? null : cardKey;
  card.value = newCard;
}; //setcard

const geometryIcon = (geomType) => {
  // vernacular map of geometry types to fontawesome classes
  let geomc = geomType ? geomType.toLowerCase() : "default";
  let iconMap = {
    point: "location-pin",
    polygon: "draw-polygon",
    multipolygon: "draw-polygon",
    linestring: "bezier-curve",
    multilinestring: "bezier-curve",
    default: "earth-oceania",
  };
  return iconMap[geomc] || iconMap["default"];
};

const submitDocumentDEV = () => {
  console.log("fake submitDocument");
  let _cbbdoc = constructDocument(),
    _cbbdocFinal,
    properties = _cbbdoc.properties;

  if (properties.provenance == "turf.buffer") {
    _cbbdocFinal = turf.centroid(_cbbdoc); //
    _cbbdocFinal.properties = properties; //put the props back
  } else {
    _cbbdocFinal = _cbbdoc;
  }
  console.log("_cbbdocFinal", _cbbdocFinal);
};

const constructDocument = () => {
  let d = new Date();
  let geo = choice.value; //chosen geometry
  geo.properties.name = cbbDocument.name; //vernaculars
  geo.properties.anno = cbbDocument.anno; //vernaculars
  geo.properties.tags = cbbDocument.tagString
    .split(",")
    .map((ts) => ts.toLowerCase().trim()); //vernaculars
  geo.properties.scnotes = "nominatim via milleria JeAKODR2"; //vernaculars
  geo.properties.cartodb_id = null; //this gets incremented by the API
  geo.properties.created_at = d.toISOString(); //vernaculars
  geo.properties.updated_at = d.toISOString(); //vernaculars

  // minimizing
  delete geo.properties.place_id;
  delete geo.properties.osm_type;
  delete geo.properties.place_rank;
  delete geo.properties.category;
  delete geo.properties.type;
  delete geo.properties.importance;
  delete geo.properties.icon;
  delete geo.properties.address;
  delete geo.properties.extratags;
  delete geo.properties.namedetails;

  return geo;
};
const submitDocument = () => {
  let _cbbJSON = constructDocument();
  let _cbbProps = _cbbJSON.properties;
  // console.log("_cbbJSON", toRaw(_cbbJSON));
  // console.log("_cbbJSONCentroid", toRaw(turf.centroid(_cbbJSON)));
  // let _cbbGeomFinal;

  // if(_cbbJSON.properties.provenance=='turf.buffer'){
  // // let propertiesCopy=_cbbJSON.properties;//copy props
  // }//if it's a point that we buffered for viz
  //  else {//it's a native geom
  //   _cbbGeomFinal=_cbbJSON;
  // }
  let _cbbGeom =
    _cbbJSON.properties.provenance == "turf.buffer"
      ? turf.centroid(choice.value)
      : choice.value; //
  // console.log("_cbbJSON", _cbbJSON);
  _cbbGeom.properties = _cbbProps; //put the props back
  // console.log("_cbbGeom", _cbbGeom);
  console.log("_cbbGeom", toRaw(_cbbGeom));

  fetch("http://localhost:3030/v3/cbb/geom", {
    credentials: "omit",
    referrer: "http://localhost:9304/",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(_cbbGeom),
    method: "POST",
  })
    .then(async (r) => {
      let rr = await r.json();
      cbbDocument.liveString = `"location_type": "${rr.location_type}","location_id": "${rr.location_id}"`; //"location_type": "point","location_id": "268",
      setRoute();
      card.value = "R";
    })
    .catch((e) => {
      console.error(e);
      error.msg = e;
      error.source = "submitDocument.POST";
      card.value = "E";
    });
};

const setChoiceGeometry = (id) => {
  // if wE hAvE A choiCE alrEaDy AND It maTcheS tHe INCoMIng ID, we nULL iT Out
  // oThERWISe wE prObe CaNdIdATES fOR tHE ID aNd set iT
  let newChoice =
    choice.value.properties.osm_id == id
      ? { properties: {} }
      : candidates.value.features.find((fea) => {
          return fea.properties.osm_id == id;
        });

  choice.value = newChoice;
  cbbDocument.name = newChoice.properties?.display_name;
};

const launderNameString = (nameString) => {
  /*
  osM dIsPLay names arE tYpICALLY prETTY GNarLy - FoR oUr PUrposES heRe ThE FiRsT fEW clausES WILl SUFFICe
  */
  return nameString
    ? nameString
        .split(",")
        .filter((propel, propeli) => {
          return propeli < 3 ? propel : null;
        })
        .join(", ")
    : "no name prop";
};

const normalizeOSM = (features) => {
  /*
  ouR OSm REsultS wiLL TYPicAlLy be a fEaTurECOlLEctION StEw OF pOLYS ANd LInEs anD PoInts
  vue-LeAFlET *sEems* LiKe iT wOULd dO pOINttOlAyER (ENABLInG circlEmARkeRs fOR THE poINtS) BUt IT aIN'T WORking
  In hErE, tHErEfORE, we JuST bUffer The PointS inTO pOLYS
  */

  return features.map((fea) => {
    // cLoNE THE pROps
    let propsClone = structuredClone(fea.properties);

    // if IT'S A PoInt rEplaCe IT W/ a BuFFeR ANd updatE tHe Bbox
    let newFeature =
      fea.geometry.type == "Point"
        ? turf.buffer(fea, 10, { units: "kilometers" })
        : fea;
    // INdICaTE oUr sHenANiGaNs IN tHE PrOpS
    newFeature.properties.provenance =
      fea.geometry.type == "Point" ? "turf.buffer" : "og";
    newFeature.bbox =
      fea.geometry.type == "Point" ? turf.bbox(newFeature) : fea.bbox;
    return newFeature;
  });
};

const animateProgress = () => {
  loading.value.progress++;
  setTimeout(() => {}, 10100);
};

const invertCoordinates = () => {
  let newQ = queryString.value
    .split(",")
    .map((c) => c.trim())
    .reverse();
  queryString.value = newQ.join(",");
};

const acceptDrop = (drop) => {
  let dro = drop[0];

  const reader = new FileReader();
  reader.loadend = (e) => {
    delete e.target.result;
  };
  reader.onload = (D) => {
    let d = JSON.parse(D.target.result);
    d.features = d.features.map((dd) => {
      dd.properties = {
        place_id: null,
        display_name: "(manual geojson)",
        osm_id: 0,
      };
      return dd;
    });

    candidates.value = d;
    cbbDocument.name = "dropped geojson";
  }; //reader.onload

  reader.readAsText(dro, "UTF-8");
}; //acceptdrop

const getCandidates = () => {
  // LOOK AT All tHIS SHIT We NEeD fOr a DumB proGRESs baR
  setTimeout(() => {}, 60100);
  setTimeout(() => {
    let intervalID = setInterval(() => {
      if (loading.value.progress === 100) {
        clearInterval(intervalID);
      } else {
        animateProgress();
      }
    }, 100); //tHis SETS the speEd OF tHE AniMatiOn
  }, 1000);

  if (!queryString.value.match(/[A-Z]/gi)) {
    //if it's just coordinates we don't need to shop anything to OSM

    let qso = queryString.value.split(",");
    let lng = parseFloat(qso[0]),
      lat = parseFloat(qso[1]);
    console.log("lng", lng);
    console.log("lat", lat);
    let features = [
      {
        type: "Feature",
        properties: { osm_id: 0, display_name: "manual coordinates" },
        bbox: [lng, lat, lng, lat],
        geometry: { type: "Point", coordinates: [lng, lat] },
      },
    ];

    let normalizedFeatures = normalizeOSM(features); // Before we Set theSE TO VUe  LETS rOOt arOuNd in ThERE and tAKE tHosE godAm fUggin pOints aND BUFfEr EM INtO polYS (LCircleMarker workaround)
    candidates.value = {
      type: "FeatureCollection",
      features: normalizedFeatures,
    };
  } //if.coordinates
  else {
    // GeT ThE stuFF
    fetch(
      `https://nominatim.openstreetmap.org/search?q=${queryString.value}&format=geojson&polygon_geojson=1&email=lennybones@ymail.com&dedupe=1&addressdetails=1&extratags=1&namedetails=1&limit=6`,
      {
        headers: { "Access-Control-Allow-Origin": "*" },
        method: "GET",
        mode: "cors",
      }
    )
      .then(async (res) => {
        setTimeout(() => {}, 60100);
        loading.value.progress = 100;
        loading.value.iz = false;
        let response = await res.json(); // to LOCAl OBject
        let features = response.features; // WORkINg cOpy oF tHE feaTuREs themseLVES
        let featuresClone = structuredClone(response.features);
        let normalizedFeatures = normalizeOSM(featuresClone); // Before we Set theSE TO VUe  LETS rOOt arOuNd in ThERE and tAKE tHosE godAm fUggin pOints aND BUFfEr EM INtO polYS (LCircleMarker workaround)
        response.features = normalizedFeatures;
        candidates.value = response;
      })
      .catch((e) => {
        console.error(e);
        error.msg = e;
        error.source = "getCandidates.GET";
      }); //fetch.catch
  } //if.coordinates.else
}; //getcandidates

/*
                      ooo        ooooo                                       .                   .o8
                      `88.       .888'                                     .o8                  "888
 .ooooo.  ooo. .oo.    888b     d'888   .ooooo.  oooo  oooo  ooo. .oo.   .o888oo  .ooooo.   .oooo888
d88' `88b `888P"Y88b   8 Y88. .P  888  d88' `88b `888  `888  `888P"Y88b    888   d88' `88b d88' `888
888   888  888   888   8  `888'   888  888   888  888   888   888   888    888   888ooo888 888   888
888   888  888   888   8    Y     888  888   888  888   888   888   888    888 . 888    .o 888   888
`Y8bod8P' o888o o888o o8o        o888o `Y8bod8P'  `V88V"V8P' o888o o888o   "888" `Y8bod8P' `Y8bod88P"


*/
onMounted(() => {
  /* ++++++++++++++++++++++++++++++++++++++++++ dropzone */
  window.addEventListener("dragenter", (e) => {
    // console.log("in dragenter, e:", e);
    dropzone.state = "drag";
    dropzone.msg = "drop fil";
  });

  window.addEventListener("dragleave", (e) => {
    e.preventDefault();
    dropzone.state = "idle";
    dropzone.msg = "fil drop";
  });

  window.addEventListener("dragover", (e) => {
    e.preventDefault();
    dropzone.state = "drag";
  });

  window.addEventListener("drop", (e) => {
    e.preventDefault();
    dropzone.state = "idle";
    dropzone.msg = "tnx";

    let fil = e.dataTransfer.files;
    acceptDrop(fil);
  });

  /* ++++++++++++++++++++++++++++++++++++++++++ /dropzone */

  /*
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys          ____ ____ ____ ____
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys         ||k |||e |||y |||s ||
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys         ||__|||__|||__|||__||
    keyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeyskeys         |/__\|/__\|/__\|/__\|
    */

  document.onkeydown = (e) => {
    e.key.toLowerCase() == "escape" && (card.value = ""); //R is different cuz we wanna copy
    // e.target.id.toLowerCase()=='queryinput' && !queryString.value.match(/[A-Z]/gi) && invertCoordinates();//coords pasted into query field we'll invert - 99% of the time that's the move
    !document.activeElement.form && card.value !== "R" && setCard(e.key); //we need to copy from R
  };

  PROPS.query && (queryString.value = PROPS.query);
  PROPS.query &&
    console.info(
      `incoming query is ${PROPS.query} so we wanna set a local querystring to ${queryString} fire the geocode here`
    );
  PROPS.query && getCandidates();

  PROPS.tags &&
    console.info(
      `incoming tags exists so we wanna decode and posthaste make it the cbbDocument.tagString`
    );
  cbbDocument.tagString = PROPS.tags ? decodeURI(PROPS.tags) : null;
  PROPS.anno &&
    console.info(
      `incoming anno exists so we wanna decode and posthaste make it the cbbDocument.anno`
    );
  cbbDocument.anno = PROPS.anno ? decodeURI(PROPS.anno) : null;
});
</script>

<style>
body {
  font-family: "overpass";
  font-weight: 800;
}

#stateError {
  background-color: rgba(230, 57, 70, 0.9);
  color: rgb(241, 250, 238);
  font-weight: 900;
  font-size: 2em;
  height: 25vh;
  top: 50%;
}
#cbbDocument {
  background-color: rgba(244, 244, 244, 0);
  height: 25vh;
  top: 50%;
}
#cbbDocumentForm {
  font-size: 3em;
}
#cbbLiveString {
  background-color: rgba(2, 2, 2, 9);
  color: white;
  font-weight: 900;
  font-size: 3em;
  height: 100vh;
  top: 0%;
}
#queryMenu {
  background-color: rgba(244, 244, 244, 0);
  height: 25vh;
  top: 40%;
}
#queryInput {
  font-size: 5em;
}

#queryResults {
  top: 2em;
  background-color: rgba(244, 244, 244, 0.9);
}

.cbb-document-input {
  font-size: 2em;
}

#footer {
  position: fixed;
  bottom: 0;
  font-size: 2em;
}
</style>
